# -*- python -*- vim:set ft=python sw=4 sts=4:

server_libs = [ 'stdc++', 'mysqlclient', 'cares', 'crypt',
    'boost_regex', 'boost_program_options', 'boost_date_time', ]

server_cxxflags = [
    '-pipe', # more efficient on multicore machines
    '-std=gnu++11', # C++11 standard w/GNU extensions

    '-Werror', # warnings are treated as errors
    '-Wall', # all recommended warnings
    '-Wpointer-arith', # things that depend on sizeof()
    '-Wcast-qual', # cast that removes const
    '-Wcast-align', # pointer cast that changes alignment
    '-Woverloaded-virtual', # virtual method w/out declaration in base class
    #'-Wconversion', # conversions that might lose data
    #'-Wextra', 
]

# debugging mode flags
server_cxxflags += [ '-g', '-O0', ]

server_subdirs = [ 'cmd', 'disc', 'game', 'misc', 'obj', 'spec', 'sys', 'task', ]

Program(target = 'grimhaven',
        source = [ 'main.cc' ] + [ Glob(d + '/*.cc') for d in server_subdirs ],
        CPPPATH = [ '.' ],
        CXXFLAGS = server_cxxflags,
        LIBS = server_libs,)
